import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-racconti',
  templateUrl: './racconti.component.html',
  styleUrls: ['./racconti.component.scss']
})
export class RaccontiComponent implements OnInit {
  
  romanzi = [
    {stringa: `C'era una volta, in un Regno lontano, una delicata fanciulla dalla riccia chioma bruna, figlia di un Mugnaio di periferia, orfana di madre. Viveva in una modesta casa di campagna fatta di mattoni in terracotta, circondata da alberi muschiati che la isolavano dal resto del mondo. Era stata maledetta alla nascita da una perfida strega con un sortilegio alquanto singolare. La sua mamma e il suo papà ne ebbero timore all'inizio, ma non appena videro in cosa consisteva, se ne rallegrarono, pensando che la malvagia strega avesse commesso un qualche errore nella sua magia. Ogni primavera, i capelli della piccola si tingevano del colore della terra fertile e su di essi crescevano dei fiori profumatissimi, la cui specie era sconosciuta a tutto il Regno. Per questo motivo, quei fiori erano una rarità e il Mugnaio, quando arrivava il tempo in cui si scioglieva la neve e le farfalle ritornavano a svolazzare tra i cespugli di azalee, si recava giornalmente insieme alla sua figliola al Mercato del Regno per vendere quei fiori mai visti prima. I contadini che passavano accanto al loro carretto rimanevano ammaliati da quel profumo e sentivano il bisogno di comprarne almeno uno tanto ne erano attratti. Le anziane chiedevano di poterli cogliere direttamente dai boccoli della fanciulla sui quali questi crescevano, ed ella era ben lieta di accogliere la proposta, considerando quella sua stranezza un dono non di suo esclusivo possesso.
    Un pomeriggio d'inizio estate, mentre padre e figlia si trovavano al Mercato per la vendita degli ultimi fiori dell'anno, la moglie del Mugnaio si recò in visita presso la sorella, la cui abitazione si trovava in un villaggio non molto lontano dal suo. Durante il viaggio, sentì che le forze le venivano a mancare, e, riuscita a raggiungere con stenti e fatiche la dimora dell'adorata sorella, vi si accasciò sull'uscio, e così comprese di non poter vivere lontana dai fiori della sua figliola. Era questa la maledizione della perfida strega.
    Allo sbocciare della primavera del suo sedicesimo anno di età, la Fanciulla si recò insieme al Mugnaio al Mercato del Regno, come facevano ogni anno, per vendere i suoi fiori. Si dà il caso che quello stesso giorno il Principe del Regno avesse deciso di fare un'uscita pubblica insieme alla sua fidanzata, la futura principessa, per rendere noto il suo amabile aspetto ai sudditi. La carrozza regale frenò la sua corsa proprio davanti al carretto del Mugnaio, poiché il principe aveva intenzione di omaggiare la sua amata con un mazzo di quei fiori la cui unicità veniva decantata dai poeti in lungo e in largo nel Regno. Li volle comperare tutti e chiese anche di poterne prendere degli altri cogliendoli direttamente dalla chioma della bella. La fanciulla, tenendo gli occhi bassi in segno di rispetto, offrì la propria testa al principe che ammirò quella meraviglia della natura. Chiese al Mugnaio di poter guardare diritto negli occhi colei che di sì tanto splendore era l'artefice, ed ella lo accontentò. Il cuore del Principe sussultò alla vista di quel volto roseo e di quegli occhi verdi come il muschio. La fanciulla era bella come una ninfa. il Principe se ne innamorò immediatamente e chiese la sua mano di fronte allo sconcerto della fidanzata e del popolo intero. Ma ella fu costretta a rifiutarlo, poiché il padre era anziano, ed ella non poteva abbandonarlo al suo destino. Erano i suoi fiori a tenerlo in vita, cosicché il destino della fanciulla era incatenato a quello del povero mugnaio. Egli non comprese le ragioni di quel rifiuto e andò via, agitando il mantello, disonorato di fronte a tutto il popolo.
    Pervaso dal dolore di quel rifiuto, il Principe mandò a chiamare la perfida strega che aveva maledetto la fanciulla, ordinandole di annullare il sortilegio. Ma ella rispose che ciò che aveva fatto era irreversibile, quindi propose al Principe un'altra soluzione. La Strega evocò allora per lui un Jinn, un demone orientale che - si diceva - potesse instillare l'Amore in qualsiasi fanciulla, portandola financo alla follia, imprigionandola in una passione senza riserve. Il principe accettò, purché alla fanciulla non venisse fatto del male e al padre venisse assicurata degna sepoltura nel cimitero dei Re. Perciò il Jinn, così istruito dalla strega, partì.
    Benché fosse un demone, a metà tra il regno terreno e quello sovraterreno, il viaggio gli risultò difficile poiché quella casetta in mattoni di terracotta era tanto isolata da essere quasi introvabile se non si conosceva il percorso per raggiungerla. Dopo strenua fatica, il Jinn raggiunse la casa della fanciulla nottetempo. Perché diventasse pazza d'amore per il Principe, egli doveva entrare dentro di lei e condurre i suoi passi verso il regno dove, alla vista del Principe, non avrebbe potuto far altro che innamorarsene perdutamente, accettandone così la proposta di matrimonio. Tuttavia, quando, sbirciando dalla finestra per accertarsi dell'effettiva identità della prodigiosa fanciulla, vide una metà del suo volto dormiente illuminato da un bagliore lunare, anche il Jinn si innamorò di lei. Un fatto contro natura che un demone potesse innamorarsi di una mortale, eppure di fronte al richiamo dell'Eros, il Jinn non poté opporsi e si trasformò in un bel giovane nelle vesti di un contadino. Bussò  alla porta del Mugnaio e chiese ospitalità per quella notte.
    Al mattino seguente, il giovane chiese al Mugnaio di potere accompagnare lui e la sua figliola al Mercato per sdebitarsi dell'aiuto concessogli, e questi accettò di buon grado, vedendo in quel generoso giovane un partito adatto per la sua figliola, a dispetto delle sue umili origini. Quando la fanciulla al risveglio lo conobbe, lo prese per mano e lo guidò nel sentiero per il mercato, come fosse un amico d'infanzia perduto da tempi immemori. Il mugnaio, finendo di sistemare il carretto per il trasporto, rimase indietro. Allora il giovane condusse i passi della fanciulla in un bosco per assaporare la frescura delle sue labbra, conscio della legge di Natura che impediva ad un demone di amare una fanciulla mortale. Ella non protestò e si lasciò guidare dalla mano sicura del giovane contadino. 
    Giunti in una radura di cui solo le ninfe boschive conoscevano l'esistenza, il Jinn prese le sue mani e se le portò al volto. Poi, poggiò lievemente le sue labbra su quelle di lei, fermando lo scorrere del tempo. La Natura, accortasi che il Tempo si era arrestato per quel bacio proibito, seppur a malincuore, non poté far altro che obbedire a se stessa e condurre il demone nell'aldilà, concessogli in ultimo di dichiarare il suo amore alla fanciulla. - Grazie a Voi, ho capito di quale forma è l'Amore ch'io sono artefice nei mortali, e per la prima e ultima volta ho potuto veramente essere me stesso in Voi- pronunziò il Jinn. Concluso il discorso, si congedò da lei e subito se lo prese la Natura, portandolo via per sempre. Ella rimase stupefatta. Sentì i fiori nella sua chioma bruna posarsi leggeri sul manto erboso per prendere infine il posto che spettava loro in quella radura incantata. Il Mugnaio invece, lontano ormai chilometri da quel luogo, si mise a vendere i fiori senza la figliola al suo fianco e non si accorse neanche della sua assenza. E il Jinn assistette dall'alto a quel miracolo d'amore, mentre la Natura se lo portava via, e comprese infine che era l'Eros a dominare la vita, non la Morte».
    L'infermiera chiuse il libro di fiabe` },
    {stringa: `C'era una volta, in un Regno lontano, una delicata fanciulla dalla riccia chioma bruna, figlia di un Mugnaio di periferia, orfana di madre. Viveva in una modesta casa di campagna fatta di mattoni in terracotta, circondata da alberi muschiati che la isolavano dal resto del mondo. Era stata maledetta alla nascita da una perfida strega con un sortilegio alquanto singolare. La sua mamma e il suo papà ne ebbero timore all'inizio, ma non appena videro in cosa consisteva, se ne rallegrarono, pensando che la malvagia strega avesse commesso un qualche errore nella sua magia. Ogni primavera, i capelli della piccola si tingevano del colore della terra fertile e su di essi crescevano dei fiori profumatissimi, la cui specie era sconosciuta a tutto il Regno. Per questo motivo, quei fiori erano una rarità e il Mugnaio, quando arrivava il tempo in cui si scioglieva la neve e le farfalle ritornavano a svolazzare tra i cespugli di azalee, si recava giornalmente insieme alla sua figliola al Mercato del Regno per vendere quei fiori mai visti prima. I contadini che passavano accanto al loro carretto rimanevano ammaliati da quel profumo e sentivano il bisogno di comprarne almeno uno tanto ne erano attratti. Le anziane chiedevano di poterli cogliere direttamente dai boccoli della fanciulla sui quali questi crescevano, ed ella era ben lieta di accogliere la proposta, considerando quella sua stranezza un dono non di suo esclusivo possesso.
    Un pomeriggio d'inizio estate, mentre padre e figlia si trovavano al Mercato per la vendita degli ultimi fiori dell'anno, la moglie del Mugnaio si recò in visita presso la sorella, la cui abitazione si trovava in un villaggio non molto lontano dal suo. Durante il viaggio, sentì che le forze le venivano a mancare, e, riuscita a raggiungere con stenti e fatiche la dimora dell'adorata sorella, vi si accasciò sull'uscio, e così comprese di non poter vivere lontana dai fiori della sua figliola. Era questa la maledizione della perfida strega.
    Allo sbocciare della primavera del suo sedicesimo anno di età, la Fanciulla si recò insieme al Mugnaio al Mercato del Regno, come facevano ogni anno, per vendere i suoi fiori. Si dà il caso che quello stesso giorno il Principe del Regno avesse deciso di fare un'uscita pubblica insieme alla sua fidanzata, la futura principessa, per rendere noto il suo amabile aspetto ai sudditi. La carrozza regale frenò la sua corsa proprio davanti al carretto del Mugnaio, poiché il principe aveva intenzione di omaggiare la sua amata con un mazzo di quei fiori la cui unicità veniva decantata dai poeti in lungo e in largo nel Regno. Li volle comperare tutti e chiese anche di poterne prendere degli altri cogliendoli direttamente dalla chioma della bella. La fanciulla, tenendo gli occhi bassi in segno di rispetto, offrì la propria testa al principe che ammirò quella meraviglia della natura. Chiese al Mugnaio di poter guardare diritto negli occhi colei che di sì tanto splendore era l'artefice, ed ella lo accontentò. Il cuore del Principe sussultò alla vista di quel volto roseo e di quegli occhi verdi come il muschio. La fanciulla era bella come una ninfa. il Principe se ne innamorò immediatamente e chiese la sua mano di fronte allo sconcerto della fidanzata e del popolo intero. Ma ella fu costretta a rifiutarlo, poiché il padre era anziano, ed ella non poteva abbandonarlo al suo destino. Erano i suoi fiori a tenerlo in vita, cosicché il destino della fanciulla era incatenato a quello del povero mugnaio. Egli non comprese le ragioni di quel rifiuto e andò via, agitando il mantello, disonorato di fronte a tutto il popolo.
    Pervaso dal dolore di quel rifiuto, il Principe mandò a chiamare la perfida strega che aveva maledetto la fanciulla, ordinandole di annullare il sortilegio. Ma ella rispose che ciò che aveva fatto era irreversibile, quindi propose al Principe un'altra soluzione. La Strega evocò allora per lui un Jinn, un demone orientale che - si diceva - potesse instillare l'Amore in qualsiasi fanciulla, portandola financo alla follia, imprigionandola in una passione senza riserve. Il principe accettò, purché alla fanciulla non venisse fatto del male e al padre venisse assicurata degna sepoltura nel cimitero dei Re. Perciò il Jinn, così istruito dalla strega, partì.
    Benché fosse un demone, a metà tra il regno terreno e quello sovraterreno, il viaggio gli risultò difficile poiché quella casetta in mattoni di terracotta era tanto isolata da essere quasi introvabile se non si conosceva il percorso per raggiungerla. Dopo strenua fatica, il Jinn raggiunse la casa della fanciulla nottetempo. Perché diventasse pazza d'amore per il Principe, egli doveva entrare dentro di lei e condurre i suoi passi verso il regno dove, alla vista del Principe, non avrebbe potuto far altro che innamorarsene perdutamente, accettandone così la proposta di matrimonio. Tuttavia, quando, sbirciando dalla finestra per accertarsi dell'effettiva identità della prodigiosa fanciulla, vide una metà del suo volto dormiente illuminato da un bagliore lunare, anche il Jinn si innamorò di lei. Un fatto contro natura che un demone potesse innamorarsi di una mortale, eppure di fronte al richiamo dell'Eros, il Jinn non poté opporsi e si trasformò in un bel giovane nelle vesti di un contadino. Bussò  alla porta del Mugnaio e chiese ospitalità per quella notte.
    Al mattino seguente, il giovane chiese al Mugnaio di potere accompagnare lui e la sua figliola al Mercato per sdebitarsi dell'aiuto concessogli, e questi accettò di buon grado, vedendo in quel generoso giovane un partito adatto per la sua figliola, a dispetto delle sue umili origini. Quando la fanciulla al risveglio lo conobbe, lo prese per mano e lo guidò nel sentiero per il mercato, come fosse un amico d'infanzia perduto da tempi immemori. Il mugnaio, finendo di sistemare il carretto per il trasporto, rimase indietro. Allora il giovane condusse i passi della fanciulla in un bosco per assaporare la frescura delle sue labbra, conscio della legge di Natura che impediva ad un demone di amare una fanciulla mortale. Ella non protestò e si lasciò guidare dalla mano sicura del giovane contadino. 
    Giunti in una radura di cui solo le ninfe boschive conoscevano l'esistenza, il Jinn prese le sue mani e se le portò al volto. Poi, poggiò lievemente le sue labbra su quelle di lei, fermando lo scorrere del tempo. La Natura, accortasi che il Tempo si era arrestato per quel bacio proibito, seppur a malincuore, non poté far altro che obbedire a se stessa e condurre il demone nell'aldilà, concessogli in ultimo di dichiarare il suo amore alla fanciulla. - Grazie a Voi, ho capito di quale forma è l'Amore ch'io sono artefice nei mortali, e per la prima e ultima volta ho potuto veramente essere me stesso in Voi- pronunziò il Jinn. Concluso il discorso, si congedò da lei e subito se lo prese la Natura, portandolo via per sempre. Ella rimase stupefatta. Sentì i fiori nella sua chioma bruna posarsi leggeri sul manto erboso per prendere infine il posto che spettava loro in quella radura incantata. Il Mugnaio invece, lontano ormai chilometri da quel luogo, si mise a vendere i fiori senza la figliola al suo fianco e non si accorse neanche della sua assenza. E il Jinn assistette dall'alto a quel miracolo d'amore, mentre la Natura se lo portava via, e comprese infine che era l'Eros a dominare la vita, non la Morte».
    L'infermiera chiuse il libro di fiabe`},
    {stringa: `C'era una volta, in un Regno lontano, una delicata fanciulla dalla riccia chioma bruna, figlia di un Mugnaio di periferia, orfana di madre. Viveva in una modesta casa di campagna fatta di mattoni in terracotta, circondata da alberi muschiati che la isolavano dal resto del mondo. Era stata maledetta alla nascita da una perfida strega con un sortilegio alquanto singolare. La sua mamma e il suo papà ne ebbero timore all'inizio, ma non appena videro in cosa consisteva, se ne rallegrarono, pensando che la malvagia strega avesse commesso un qualche errore nella sua magia. Ogni primavera, i capelli della piccola si tingevano del colore della terra fertile e su di essi crescevano dei fiori profumatissimi, la cui specie era sconosciuta a tutto il Regno. Per questo motivo, quei fiori erano una rarità e il Mugnaio, quando arrivava il tempo in cui si scioglieva la neve e le farfalle ritornavano a svolazzare tra i cespugli di azalee, si recava giornalmente insieme alla sua figliola al Mercato del Regno per vendere quei fiori mai visti prima. I contadini che passavano accanto al loro carretto rimanevano ammaliati da quel profumo e sentivano il bisogno di comprarne almeno uno tanto ne erano attratti. Le anziane chiedevano di poterli cogliere direttamente dai boccoli della fanciulla sui quali questi crescevano, ed ella era ben lieta di accogliere la proposta, considerando quella sua stranezza un dono non di suo esclusivo possesso.
    Un pomeriggio d'inizio estate, mentre padre e figlia si trovavano al Mercato per la vendita degli ultimi fiori dell'anno, la moglie del Mugnaio si recò in visita presso la sorella, la cui abitazione si trovava in un villaggio non molto lontano dal suo. Durante il viaggio, sentì che le forze le venivano a mancare, e, riuscita a raggiungere con stenti e fatiche la dimora dell'adorata sorella, vi si accasciò sull'uscio, e così comprese di non poter vivere lontana dai fiori della sua figliola. Era questa la maledizione della perfida strega.
    Allo sbocciare della primavera del suo sedicesimo anno di età, la Fanciulla si recò insieme al Mugnaio al Mercato del Regno, come facevano ogni anno, per vendere i suoi fiori. Si dà il caso che quello stesso giorno il Principe del Regno avesse deciso di fare un'uscita pubblica insieme alla sua fidanzata, la futura principessa, per rendere noto il suo amabile aspetto ai sudditi. La carrozza regale frenò la sua corsa proprio davanti al carretto del Mugnaio, poiché il principe aveva intenzione di omaggiare la sua amata con un mazzo di quei fiori la cui unicità veniva decantata dai poeti in lungo e in largo nel Regno. Li volle comperare tutti e chiese anche di poterne prendere degli altri cogliendoli direttamente dalla chioma della bella. La fanciulla, tenendo gli occhi bassi in segno di rispetto, offrì la propria testa al principe che ammirò quella meraviglia della natura. Chiese al Mugnaio di poter guardare diritto negli occhi colei che di sì tanto splendore era l'artefice, ed ella lo accontentò. Il cuore del Principe sussultò alla vista di quel volto roseo e di quegli occhi verdi come il muschio. La fanciulla era bella come una ninfa. il Principe se ne innamorò immediatamente e chiese la sua mano di fronte allo sconcerto della fidanzata e del popolo intero. Ma ella fu costretta a rifiutarlo, poiché il padre era anziano, ed ella non poteva abbandonarlo al suo destino. Erano i suoi fiori a tenerlo in vita, cosicché il destino della fanciulla era incatenato a quello del povero mugnaio. Egli non comprese le ragioni di quel rifiuto e andò via, agitando il mantello, disonorato di fronte a tutto il popolo.
    Pervaso dal dolore di quel rifiuto, il Principe mandò a chiamare la perfida strega che aveva maledetto la fanciulla, ordinandole di annullare il sortilegio. Ma ella rispose che ciò che aveva fatto era irreversibile, quindi propose al Principe un'altra soluzione. La Strega evocò allora per lui un Jinn, un demone orientale che - si diceva - potesse instillare l'Amore in qualsiasi fanciulla, portandola financo alla follia, imprigionandola in una passione senza riserve. Il principe accettò, purché alla fanciulla non venisse fatto del male e al padre venisse assicurata degna sepoltura nel cimitero dei Re. Perciò il Jinn, così istruito dalla strega, partì.
    Benché fosse un demone, a metà tra il regno terreno e quello sovraterreno, il viaggio gli risultò difficile poiché quella casetta in mattoni di terracotta era tanto isolata da essere quasi introvabile se non si conosceva il percorso per raggiungerla. Dopo strenua fatica, il Jinn raggiunse la casa della fanciulla nottetempo. Perché diventasse pazza d'amore per il Principe, egli doveva entrare dentro di lei e condurre i suoi passi verso il regno dove, alla vista del Principe, non avrebbe potuto far altro che innamorarsene perdutamente, accettandone così la proposta di matrimonio. Tuttavia, quando, sbirciando dalla finestra per accertarsi dell'effettiva identità della prodigiosa fanciulla, vide una metà del suo volto dormiente illuminato da un bagliore lunare, anche il Jinn si innamorò di lei. Un fatto contro natura che un demone potesse innamorarsi di una mortale, eppure di fronte al richiamo dell'Eros, il Jinn non poté opporsi e si trasformò in un bel giovane nelle vesti di un contadino. Bussò  alla porta del Mugnaio e chiese ospitalità per quella notte.
    Al mattino seguente, il giovane chiese al Mugnaio di potere accompagnare lui e la sua figliola al Mercato per sdebitarsi dell'aiuto concessogli, e questi accettò di buon grado, vedendo in quel generoso giovane un partito adatto per la sua figliola, a dispetto delle sue umili origini. Quando la fanciulla al risveglio lo conobbe, lo prese per mano e lo guidò nel sentiero per il mercato, come fosse un amico d'infanzia perduto da tempi immemori. Il mugnaio, finendo di sistemare il carretto per il trasporto, rimase indietro. Allora il giovane condusse i passi della fanciulla in un bosco per assaporare la frescura delle sue labbra, conscio della legge di Natura che impediva ad un demone di amare una fanciulla mortale. Ella non protestò e si lasciò guidare dalla mano sicura del giovane contadino. 
    Giunti in una radura di cui solo le ninfe boschive conoscevano l'esistenza, il Jinn prese le sue mani e se le portò al volto. Poi, poggiò lievemente le sue labbra su quelle di lei, fermando lo scorrere del tempo. La Natura, accortasi che il Tempo si era arrestato per quel bacio proibito, seppur a malincuore, non poté far altro che obbedire a se stessa e condurre il demone nell'aldilà, concessogli in ultimo di dichiarare il suo amore alla fanciulla. - Grazie a Voi, ho capito di quale forma è l'Amore ch'io sono artefice nei mortali, e per la prima e ultima volta ho potuto veramente essere me stesso in Voi- pronunziò il Jinn. Concluso il discorso, si congedò da lei e subito se lo prese la Natura, portandolo via per sempre. Ella rimase stupefatta. Sentì i fiori nella sua chioma bruna posarsi leggeri sul manto erboso per prendere infine il posto che spettava loro in quella radura incantata. Il Mugnaio invece, lontano ormai chilometri da quel luogo, si mise a vendere i fiori senza la figliola al suo fianco e non si accorse neanche della sua assenza. E il Jinn assistette dall'alto a quel miracolo d'amore, mentre la Natura se lo portava via, e comprese infine che era l'Eros a dominare la vita, non la Morte».
    L'infermiera chiuse il libro di fiabe`}
  ]
  
  
  racconti: object[] = [
      {
          'title': "Dell'Eros e dei suoi Demoni",
          'text': `C'era una volta, in un Regno lontano, una delicata fanciulla dalla riccia chioma bruna, figlia di un Mugnaio di periferia, orfana di madre. Viveva in una modesta casa di campagna fatta di mattoni in terracotta, circondata da alberi muschiati che la isolavano dal resto del mondo. Era stata maledetta alla nascita da una perfida strega con un sortilegio alquanto singolare. La sua mamma e il suo papà ne ebbero timore all'inizio, ma non appena videro in cosa consisteva, se ne rallegrarono, pensando che la malvagia strega avesse commesso un qualche errore nella sua magia. Ogni primavera, i capelli della piccola si tingevano del colore della terra fertile e su di essi crescevano dei fiori profumatissimi, la cui specie era sconosciuta a tutto il Regno. Per questo motivo, quei fiori erano una rarità e il Mugnaio, quando arrivava il tempo in cui si scioglieva la neve e le farfalle ritornavano a svolazzare tra i cespugli di azalee, si recava giornalmente insieme alla sua figliola al Mercato del Regno per vendere quei fiori mai visti prima. I contadini che passavano accanto al loro carretto rimanevano ammaliati da quel profumo e sentivano il bisogno di comprarne almeno uno tanto ne erano attratti. Le anziane chiedevano di poterli cogliere direttamente dai boccoli della fanciulla sui quali questi crescevano, ed ella era ben lieta di accogliere la proposta, considerando quella sua stranezza un dono non di suo esclusivo possesso.
          Un pomeriggio d'inizio estate, mentre padre e figlia si trovavano al Mercato per la vendita degli ultimi fiori dell'anno, la moglie del Mugnaio si recò in visita presso la sorella, la cui abitazione si trovava in un villaggio non molto lontano dal suo. Durante il viaggio, sentì che le forze le venivano a mancare, e, riuscita a raggiungere con stenti e fatiche la dimora dell'adorata sorella, vi si accasciò sull'uscio, e così comprese di non poter vivere lontana dai fiori della sua figliola. Era questa la maledizione della perfida strega.
          Allo sbocciare della primavera del suo sedicesimo anno di età, la Fanciulla si recò insieme al Mugnaio al Mercato del Regno, come facevano ogni anno, per vendere i suoi fiori. Si dà il caso che quello stesso giorno il Principe del Regno avesse deciso di fare un'uscita pubblica insieme alla sua fidanzata, la futura principessa, per rendere noto il suo amabile aspetto ai sudditi. La carrozza regale frenò la sua corsa proprio davanti al carretto del Mugnaio, poiché il principe aveva intenzione di omaggiare la sua amata con un mazzo di quei fiori la cui unicità veniva decantata dai poeti in lungo e in largo nel Regno. Li volle comperare tutti e chiese anche di poterne prendere degli altri cogliendoli direttamente dalla chioma della bella. La fanciulla, tenendo gli occhi bassi in segno di rispetto, offrì la propria testa al principe che ammirò quella meraviglia della natura. Chiese al Mugnaio di poter guardare diritto negli occhi colei che di sì tanto splendore era l'artefice, ed ella lo accontentò. Il cuore del Principe sussultò alla vista di quel volto roseo e di quegli occhi verdi come il muschio. La fanciulla era bella come una ninfa. il Principe se ne innamorò immediatamente e chiese la sua mano di fronte allo sconcerto della fidanzata e del popolo intero. Ma ella fu costretta a rifiutarlo, poiché il padre era anziano, ed ella non poteva abbandonarlo al suo destino. Erano i suoi fiori a tenerlo in vita, cosicché il destino della fanciulla era incatenato a quello del povero mugnaio. Egli non comprese le ragioni di quel rifiuto e andò via, agitando il mantello, disonorato di fronte a tutto il popolo.
          Pervaso dal dolore di quel rifiuto, il Principe mandò a chiamare la perfida strega che aveva maledetto la fanciulla, ordinandole di annullare il sortilegio. Ma ella rispose che ciò che aveva fatto era irreversibile, quindi propose al Principe un'altra soluzione. La Strega evocò allora per lui un Jinn, un demone orientale che - si diceva - potesse instillare l'Amore in qualsiasi fanciulla, portandola financo alla follia, imprigionandola in una passione senza riserve. Il principe accettò, purché alla fanciulla non venisse fatto del male e al padre venisse assicurata degna sepoltura nel cimitero dei Re. Perciò il Jinn, così istruito dalla strega, partì.
          Benché fosse un demone, a metà tra il regno terreno e quello sovraterreno, il viaggio gli risultò difficile poiché quella casetta in mattoni di terracotta era tanto isolata da essere quasi introvabile se non si conosceva il percorso per raggiungerla. Dopo strenua fatica, il Jinn raggiunse la casa della fanciulla nottetempo. Perché diventasse pazza d'amore per il Principe, egli doveva entrare dentro di lei e condurre i suoi passi verso il regno dove, alla vista del Principe, non avrebbe potuto far altro che innamorarsene perdutamente, accettandone così la proposta di matrimonio. Tuttavia, quando, sbirciando dalla finestra per accertarsi dell'effettiva identità della prodigiosa fanciulla, vide una metà del suo volto dormiente illuminato da un bagliore lunare, anche il Jinn si innamorò di lei. Un fatto contro natura che un demone potesse innamorarsi di una mortale, eppure di fronte al richiamo dell'Eros, il Jinn non poté opporsi e si trasformò in un bel giovane nelle vesti di un contadino. Bussò  alla porta del Mugnaio e chiese ospitalità per quella notte.
          Al mattino seguente, il giovane chiese al Mugnaio di potere accompagnare lui e la sua figliola al Mercato per sdebitarsi dell'aiuto concessogli, e questi accettò di buon grado, vedendo in quel generoso giovane un partito adatto per la sua figliola, a dispetto delle sue umili origini. Quando la fanciulla al risveglio lo conobbe, lo prese per mano e lo guidò nel sentiero per il mercato, come fosse un amico d'infanzia perduto da tempi immemori. Il mugnaio, finendo di sistemare il carretto per il trasporto, rimase indietro. Allora il giovane condusse i passi della fanciulla in un bosco per assaporare la frescura delle sue labbra, conscio della legge di Natura che impediva ad un demone di amare una fanciulla mortale. Ella non protestò e si lasciò guidare dalla mano sicura del giovane contadino. 
          Giunti in una radura di cui solo le ninfe boschive conoscevano l'esistenza, il Jinn prese le sue mani e se le portò al volto. Poi, poggiò lievemente le sue labbra su quelle di lei, fermando lo scorrere del tempo. La Natura, accortasi che il Tempo si era arrestato per quel bacio proibito, seppur a malincuore, non poté far altro che obbedire a se stessa e condurre il demone nell'aldilà, concessogli in ultimo di dichiarare il suo amore alla fanciulla. - Grazie a Voi, ho capito di quale forma è l'Amore ch'io sono artefice nei mortali, e per la prima e ultima volta ho potuto veramente essere me stesso in Voi- pronunziò il Jinn. Concluso il discorso, si congedò da lei e subito se lo prese la Natura, portandolo via per sempre. Ella rimase stupefatta. Sentì i fiori nella sua chioma bruna posarsi leggeri sul manto erboso per prendere infine il posto che spettava loro in quella radura incantata. Il Mugnaio invece, lontano ormai chilometri da quel luogo, si mise a vendere i fiori senza la figliola al suo fianco e non si accorse neanche della sua assenza. E il Jinn assistette dall'alto a quel miracolo d'amore, mentre la Natura se lo portava via, e comprese infine che era l'Eros a dominare la vita, non la Morte».
          L'infermiera chiuse il libro di fiabe e osservò quel candido volto che giaceva sul lettino d'ospedale intubato ormai da settimane. L'Amore l'aveva rapita piano piano, poi d'un colpo tutt'insieme. Non ci aveva mai parlato. Quell'uomo era arrivato lì già privo di coscienza. E non poteva credere a quello che sentiva per lui, cercando di trovare una spiegazione per qualcosa che non ne aveva. Gli leggeva una fiaba ogni giorno, all'ora del crepuscolo, quando le sue lacrime d'assurdo erano visibili a lei soltanto. Sentiva di non poterci rinunciare e che, se gliel'avessero concesso, sarebbe rimasta davanti a quel lettino a farsi bruciare le viscere dall'Amore per sempre.`
     },
     {
         'title': "Il cappello",
         'text': ""
     },
     {
         'title':"Le occhiaie",
         'text': ""
     }
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
